envVars:
  - name: "TEST_MODE"
    value: "True"
  - name: "SLACK_AUTH_TOKEN"
    value: "xoxb-229292929292-2929292929292-aYg4i2ajev35JUERvytFKhp5"
  - name: "SLACK_APP_TOKEN"
    value: "xapp-1-A0A0A0A0A0A-2929292929292-aYg4i2ajev35JUERvytFKhp5aYg4i2ajev35JUERvytFKhp56fb5252525252525"
  - name: "DATA_DIR"
    value: "/tmp"
