{{- if .Values.cryptopricey.secret.create }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.cryptopricey.secret.name }}
  name: {{ .Values.cryptopricey.secret.name }}
{{- else }}
  name: {{ .Release.Name }}
{{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  .env: {{ .Values.cryptopricey.secret.contents | b64enc }}
{{- end }}
