# This is the default values file for cryptopricey
deployment:
  replicas: 1

cryptopricey:
  secret:
    create: false
    # name: ""
    # The following are only used if create=true
    # contents: |
    #   slackAuthToken: "xoxb-229292929292-2929292929292-aYg4i2ajev35JUERvytFKhp5"
    #   slackAppToken: "xapp-1-A0A0A0A0A0A-2929292929292-aYg4i2ajev35JUERvytFKhp5aYg4i2ajev35JUERvytFKhp56fb5252525252525"
    #   dataDir: "/tmp"

image:
  repository: "cloudstruct/cryptopricey"
  tag: "1.1.0"
  pullPolicy: "IfNotPresent"

ingressRoute: {}
  # name: cryptopricey
  # annotations:
  #   external-dns: true
  # tls:
  #   secretName: ""
  # host: my.oauth.com

service:
  create: true
  name: cryptopricey
  port: 8080
  portName: http
  type: ClusterIP

serviceAccount:
  create: true
  name: "cryptopricey"
  annotations: {}
  labels: {}

envVars: []
